



# version: 2.1

# orbs:
#   node: circleci/node@5.1.0
#   slack: circleci/slack@4.10.1# jobs:
#   build-and-test:
#     docker:
#       - image: cypress/base:18.16.0
#     steps:
#       - checkout
#       - node/install-packages
#       - run:
#           name: Run tests
#           command: npx cypress run
#       - run:
#           name: Run cloud
#           command:  npx cypress run --record --key d1b0fde7-627e-4cf5-8075-db57d29a3d21
#           #Here, to start some changes
#       - run:
#           name: Run Cypress tests and generate report
#           command: npm run test:report

#       # - persist_to_workspace:
#       #     root: /tmp/workspace
#       #     paths:
#       #       - cypress/reports
#       # - slack/notify:
#       #     event: pass
#       #     channel: "#general"   # Replace this with the desired channel or user
#       #     template: success_tagged_deploy_1
#       #     attach_workspace:
#       #       at: /tmp/workspace
#       # - slack/notify:
#       #     event: fail
#       #     mentions: "p-x2u3774.slack.com"  # Mention a specific user
#       #     channel: "p"    # Replace this with the desired channel or user
#       #     template: basic_fail_1
#       #     attach_workspace:
#       #       at: /tmp/workspace
#       # - slack:
#       #     message: "Cypress tests complete. ${status} tests ran, ${failed} tests failed."
#       #     channel: "#cypress"

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build-and-test

#       - my_hourly_job:
#           filters:
#             branches:
#               only:
#                 - main  # Adjust the branch if needed
#       - my_daily_job:
#           triggers:
#             - schedule:
#                 cron: "0 0 * * *"

version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.10.1

jobs:
  build-and-test:
    docker:
      - image: cypress/base:18.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npx cypress run
      - run:
          name: Run cloud
          command: npx cypress run --record --key d1b0fde7-627e-4cf5-8075-db57d29a3d21
      - run:
          name: Run Cypress tests and generate report
          command: npm run test:report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test:

      # - schedule:
      #     cron: "0 * * * *"
      #     filters:
      #       branches:
      #         only: 
      #             - main
      #             - prashant
